// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaePC935J9iPz_rTD0a1Or8YzpWh5rDM',
    appId: '1:751497855436:web:92bbbcc93cfe6ba2f75d69',
    messagingSenderId: '751497855436',
    projectId: 'wan-pak',
    authDomain: 'wan-pak.firebaseapp.com',
    storageBucket: 'wan-pak.firebasestorage.app',
    measurementId: 'G-GZM126QKK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlSjwLt9_0G1-Z_qzKhIjxjxH4Ab_w7So',
    appId: '1:751497855436:android:d2c1a31af965ef8af75d69',
    messagingSenderId: '751497855436',
    projectId: 'wan-pak',
    storageBucket: 'wan-pak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgyUEKBrkQGLfjqN_7HAoB203737hjaVs',
    appId: '1:751497855436:ios:cf5b095fca438d03f75d69',
    messagingSenderId: '751497855436',
    projectId: 'wan-pak',
    storageBucket: 'wan-pak.firebasestorage.app',
    iosBundleId: 'com.example.wanPakHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgyUEKBrkQGLfjqN_7HAoB203737hjaVs',
    appId: '1:751497855436:ios:cf5b095fca438d03f75d69',
    messagingSenderId: '751497855436',
    projectId: 'wan-pak',
    storageBucket: 'wan-pak.firebasestorage.app',
    iosBundleId: 'com.example.wanPakHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByaePC935J9iPz_rTD0a1Or8YzpWh5rDM',
    appId: '1:751497855436:web:248730f64b4a7349f75d69',
    messagingSenderId: '751497855436',
    projectId: 'wan-pak',
    authDomain: 'wan-pak.firebaseapp.com',
    storageBucket: 'wan-pak.firebasestorage.app',
    measurementId: 'G-1062Q4V3K7',
  );
}
